base_config:
- configs/acoustic.yaml
dictionaries:
  gyu: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/dictionary-gyu-vocalset-lexical.txt
datasets:
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/gyu_all_segmented
  speaker: gyu
  language: gyu
  spk_id: 20
  test_prefixes:
  - gyu_real_000110_seg00
  - gyu_real_000110_seg01
  - gyu_real_000110_seg02
  - gyu_real_000110_seg03
  - gyu_real_000110_seg04
  - gyu_real_000110_seg05
  - gyu_real_000110_seg06
  - gyu_real_000110_seg07
  - gyu_real_000110_seg08
  - gyu_real_000110_seg09
  - gyu_real_000110_seg10
  - gyu_real_000110_seg11
  - gyu_real_000110_seg12
  - gyu_real_000110_seg13
  - gyu_real_000110_seg14
  - gyu_real_000110_seg15
  - gyu_real_000110_seg16
  - gyu_real_000110_seg17
  - gyu_real_000110_seg18
  - gyu_real_000110_seg19
  - gyu_real_000110_seg20
  - gyu_real_000110_seg21
  - gyu_real_000110_seg22
  - gyu_real_000110_seg23
  - gyu_real_000110_seg24
  - gyu_real_000110_seg25
  - gyu_real_000110_seg26
  - gyu_real_000110_seg27
  - gyu_real_000110_seg28
  - gyu_real_000110_seg29
  - gyu_real_000110_seg30
  - gyu_real_000110_seg31
  - gyu_real_000110_seg32
  - gyu_real_000110_seg33
  - gyu_real_000110_seg34
  - gyu_real_000110_seg35
  - gyu_real_000110_seg36
  - gyu_real_000110_seg37
  - gyu_real_000110_seg38
  - gyu_real_000110_seg39
  - gyu_real_000115_seg00
  - gyu_real_000115_seg01
  - gyu_real_000115_seg02
  - gyu_real_000115_seg03
  - gyu_real_000115_seg04
  - gyu_real_000115_seg05
  - gyu_real_000115_seg06
  - gyu_real_000115_seg07
  - gyu_real_000115_seg08
  - gyu_real_000115_seg09
  - gyu_real_000115_seg10
  - gyu_real_000115_seg11
  - gyu_real_000115_seg12
  - gyu_real_000115_seg13
  - gyu_real_000115_seg14
  - gyu_real_000115_seg15
  - gyu_real_000115_seg16
  - gyu_real_000120_seg00
  - gyu_real_000120_seg01
  - gyu_real_000120_seg02
  - gyu_real_000120_seg03
  - gyu_real_000120_seg04
  - gyu_real_000120_seg05
  - gyu_real_000120_seg06
  - gyu_real_000120_seg07
  - gyu_real_000125_seg00
  - gyu_real_000125_seg01
  - gyu_real_000125_seg02
  - gyu_real_000125_seg03
  - gyu_real_000125_seg04
  - gyu_real_000125_seg05
  - gyu_real_000130_seg00
  - gyu_real_000130_seg01
  - gyu_real_000130_seg02
  - gyu_real_000130_seg03
  - gyu_real_000130_seg04
  - gyu_real_000130_seg05
  - gyu_real_000130_seg06
  - gyu_real_000130_seg07
  - gyu_real_000135_seg00
  - gyu_real_000135_seg01
  - gyu_real_000135_seg02
  - gyu_real_000135_seg03
  - gyu_real_000135_seg04
  - gyu_real_000135_seg05
  - gyu_real_000140_seg00
  - gyu_real_000140_seg01
  - gyu_real_000140_seg02
  - gyu_real_000140_seg03
  - gyu_real_000140_seg04
  - gyu_real_000140_seg05
  - gyu_real_000140_seg06
  - gyu_real_000145_seg00
  - gyu_real_000145_seg01
  - gyu_real_000145_seg02
  - gyu_real_000145_seg03
  - gyu_real_000145_seg04
  - gyu_real_000145_seg05
  - gyu_real_000145_seg06
  - gyu_real_000145_seg07
  - gyu_real_000145_seg08
  - gyu_real_000154_seg00
  - gyu_real_000165_seg00
  - gyu_real_000165_seg01
  - gyu_real_000198_seg00
  - gyu_real_000204_seg00
  - gyu_real_000204_seg01
  - gyu_real_000204_seg02
  - gyu_real_000204_seg03
  - gyu_real_000209_seg00
  - gyu_real_000209_seg01
  - gyu_real_000209_seg02
  - gyu_real_000209_seg03
  - gyu_real_000209_seg04
  - gyu_real_000209_seg05
  - gyu_real_000220_seg00
  - gyu_real_000220_seg01
  - gyu_real_000220_seg02
  - gyu_real_000220_seg03
  - gyu_real_000220_seg04
  - gyu_real_000220_seg05
  - gyu_real_000220_seg06
  - gyu_real_000220_seg07
  - gyu_real_000220_seg08
  - gyu_real_000221_seg00
  - gyu_real_000221_seg01
  - gyu_real_000221_seg02
  - gyu_real_000221_seg03
  - gyu_real_000221_seg04
  - gyu_real_000221_seg05
  - gyu_real_000221_seg06
  - gyu_real_000221_seg07
  - gyu_real_000221_seg08
  - gyu_real_000221_seg09
  - gyu_real_000221_seg10
  - gyu_real_000221_seg11
  - gyu_real_000221_seg12
  - gyu_real_000221_seg13
  - gyu_real_000221_seg14
  - gyu_real_000221_seg15
  - gyu_real_000230_seg00
  - gyu_real_000230_seg01
  - gyu_real_000235_seg00
  - gyu_real_000235_seg01
  - gyu_real_000235_seg02
  - gyu_real_000235_seg03
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/female9
  speaker: female9
  spk_id: 8
  language: gyu
  test_prefixes:
  - vocalset_female9_row_vibrato_0
  - vocalset_female9_row_vibrato_1
  - vocalset_female9_row_straight_0
  - vocalset_female9_row_straight_1
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/female7
  speaker: female7
  spk_id: 6
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/female1
  speaker: female1
  spk_id: 0
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/female6
  speaker: female6
  spk_id: 5
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/female8
  speaker: female8
  spk_id: 7
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/male4
  speaker: male4
  spk_id: 14
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/male3
  speaker: male3
  spk_id: 13
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/male2
  speaker: male2
  spk_id: 12
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/male5
  speaker: male5
  spk_id: 15
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/male10
  speaker: male10
  spk_id: 10
  language: gyu
  test_prefixes:
  - vocalset_male10_row_straight_0
  - vocalset_male10_row_straight_1
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/male11
  speaker: male11
  spk_id: 11
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/female3
  speaker: female3
  spk_id: 2
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/female4
  speaker: female4
  spk_id: 3
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/female5
  speaker: female5
  spk_id: 4
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/female2
  speaker: female2
  spk_id: 1
  language: gyu
  test_prefixes:
  - vocalset_female2_row_vibrato_0
  - vocalset_female2_row_vibrato_1
  - vocalset_female2_row_straight_0
  - vocalset_female2_row_straight_1
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/male7
  speaker: male7
  spk_id: 17
  language: gyu
  test_prefixes:
  - vocalset_male7_row_vibrato_0
  - vocalset_male7_row_vibrato_1
  - vocalset_male7_row_straight_0
  - vocalset_male7_row_straight_1
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/male9
  speaker: male9
  spk_id: 19
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/male8
  speaker: male8
  spk_id: 18
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/male6
  speaker: male6
  spk_id: 16
  language: gyu
  test_prefixes: []
- raw_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/raw/vocalset_lexical/male1
  speaker: male1
  spk_id: 9
  language: gyu
  test_prefixes: []
binary_data_dir: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/binary_vocalset_lexical
use_spk_id: true
num_spk: 21
use_lang_id: false
num_lang: 1
pe: rmvpe
pe_ckpt: /home/kotori9/code/gyukaro/data/cache/diffsinger-assets/rmvpe/model.pt
hnsep: world
use_energy_embed: false
use_breathiness_embed: false
use_voicing_embed: false
use_tension_embed: false
vocoder: NsfHifiGAN
vocoder_ckpt: /home/kotori9/code/gyukaro/data/external/work/diffsinger_score_native/vocoder_exported/model.ckpt
binarization_args:
  num_workers: 4
  shuffle: true
finetune_enabled: true
finetune_ckpt_path: /home/kotori9/code/gyukaro/data/cache/diffsinger/checkpoints/gyu_score_native_vocalset_lexical_vocab.ckpt
finetune_ignored_params: []
finetune_strict_shapes: true
freezing_enabled: true
frozen_params:
- model.fs2.stretch_embed
- model.fs2.stretch_embed_rnn
- model.fs2.dur_embed
- model.fs2.pitch_embed
max_updates: 300
val_check_interval: 100
num_valid_plots: 0
val_with_vocoder: false
max_batch_frames: 20000
max_batch_size: 8
num_ckpt_keep: 3
optimizer_args:
  lr: 1.0e-05
