#!/usr/bin/env python3
"""Generate current hybrid training, evaluation, and final reports."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import subprocess


def read(path: str) -> dict:
    return json.loads(Path(path).read_text())


def count(path: str) -> int:
    return sum(bool(line) for line in Path(path).read_text().splitlines())


def value(number: float | None) -> str:
    return "unavailable" if number is None else f"{number:.4f}"


def main() -> None:
    training = read("artifacts/reports/hybrid_training.json")
    evaluation = read("artifacts/reports/baseline_hybrid_evaluation.json")["scores"]
    sustain = read("artifacts/reports/hybrid_sustained_vowels.json")["results"]
    accepted = count("data/manifests/pseudo_singing_accepted.jsonl")
    checkpoint = Path("checkpoints/gyu_hybrid_v0.2.pt")
    archive = Path("artifacts/package/gyu-hybrid-singer-v0.2-experimental.zip")
    checkpoint_hash = hashlib.sha256(checkpoint.read_bytes()).hexdigest()
    archive_hash = hashlib.sha256(archive.read_bytes()).hexdigest()
    commit = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    last = training["history"][-1]
    training_text = f"""# Training v0.2 report

Generated by `scripts/report_hybrid_v2.py`. CUDA run: 1,200 steps, AdamW LR `2e-4`, batch 1. Train rows: {training['real_rows']} real GYU plus {training['pseudo_rows']} accepted low-trust pseudo-singing; validation/test: 8/5. Teacher representation rows: {training['teacher_rows']}, coefficient {training['teacher_loss_weight']}.

Pseudo corpus: {accepted}/100 ACE-Step (Apache-2.0) lyric-vocal candidates passed RMVPE, duration, WavLM, Whisper, and language gates after Apache-2.0 SoulX SVC. Each accepted row has trust 0.20 and inferred RMVPE-pitch/duration score labels; it is not source annotation.

Final loss: total {last['loss']}, flow {last['flow']}, pitch {last['pitch']}, teacher {last['teacher']}. This is optimization evidence only, not singing-quality proof. Checkpoint SHA-256: `{checkpoint_hash}`.
"""
    lines = ["# Evaluation v0.2 report", "", "Generated by `scripts/evaluate_baseline_hybrid.py` and `scripts/report_hybrid_v2.py`. Identical short KO/EN/JA scores; RMVPE, WavLM, Whisper, and boundary metrics. This is not listening-test evidence.", "", "| Language | Renderer | F0 corr | cents MAE | WavLM | ASR similarity |", "|---|---|---:|---:|---:|---:|"]
    for language, results in evaluation.items():
        for renderer, result in results.items():
            lines.append(f"| {language.upper()} | {renderer} | {value(result['rmvpe_f0_correlation'])} | {value(result['note_pitch_mae_cents'])} | {value(result['speaker_similarity_wavlm'])} | {value(result['asr_lyric_similarity'])} |")
    sustain_text = ", ".join(f"{language.upper()} voiced {result['voiced_ratio']}, F0 CV {result['f0_cv']}, median {result['median_f0_hz']} Hz" for language, result in sustain.items())
    evaluation_text = "\n".join(lines) + f"\n\n3-second held-vowel benchmark (SoulX RMVPE): {sustain_text}. Stable voiced output exists, but median F0 is not the requested C4 and pitch does not meet v1 quality bars.\n\nJapanese output is a frontend/runtime exercise, not a quality claim.\n"
    final_text = f"""Overall status: experimental neural phrase SVS; quality gate fail, not v1.
Current stage: GYU Hybrid Singer v0.2-experimental.
Package: `artifacts/package/gyu-hybrid-singer-v0.2-experimental.zip`
Package SHA-256: `{archive_hash}`
Git commit: `{commit}` (report generation source revision)
Hybrid SVS checkpoint: `checkpoints/gyu_hybrid_v0.2.pt`, SHA-256 `{checkpoint_hash}`
Trainable parameters: 762,018.
Phrase-level neural generation: yes; one full phrase frame tensor, conditional-flow latent sample, frozen codec decode.
Phoneme-note alignment: yes; deterministic language-aware note-frame mapping; real/pseudo bootstrap labels marked inferred.
Continuous pitch conditioning: yes; MIDI, curve/residual, UV mask, masked log-F0 loss; current generated F0 quality fails.
Teacher distillation gradient verified: yes; timbre and language encoder non-zero gradients under teacher loss.
Pseudo-singing used in training: yes; {training['pseudo_rows']} accepted low-trust train rows, 100 candidates/{accepted} accepted overall.
Blurred boundary active: yes; `BlurredBoundaryEncoder` is in condition path.
Conditional flow matching active: yes; rectified-flow target/noise objective and Euler phrase sampling.
Style conditioning active: yes; preset plus five controls; not calibrated.
OpenUtau integration: executable USTX parser/exporter plus resident renderer POST; native renderer registration not implemented.
Korean: runtime/frontend exercised; quality not accepted.
English: runtime/frontend exercised; quality not accepted.
Japanese: runtime/frontend exercised; quality not accepted.

# What was inherited from Stage 0

132 indexed recordings, canonical 48 kHz masters, real phrase anchors, MOSS baseline, teacher manifests, and baseline resident runtime remain preserved. `baseline_renderer.py` and `neural_renderer.py` are comparison backends only.

# What was actually implemented in this Goal

`TriSingerModel` connects unified phoneme, language, score, blurred-boundary, timbre, style, pitch, conditional-flow, and acoustic-latent decoder modules. Protocol v2, a resident hybrid renderer, trilingual frontend, hard no-DSP path test, and executable USTX bridge are present.

# Exact hybrid forward path

Protocol v2 normalization converts beats to seconds. Frontend and deterministic note alignment build one full phrase frame tensor. `TriSingerModel.condition` fuses content, score, blurred boundaries, reference timbre, style, and continuous pitch. `ConditionalFlowTransformer` samples one latent phrase; `SingingDecoder` adds learned acoustic bias; frozen `MossCodecDecoder` emits 48 kHz WAV. No hybrid call uses per-note TTS, pitch shift, or phase vocoder.

# Exact data flow by dataset type

Real GYU rows use inferred timing plus cached RMVPE F0, codec latents, and trust 1.0. ACE-Step lyric-vocal then SoulX SVC rows use 48 kHz synthetic audio, inferred RMVPE pitch/duration labels, and trust 0.20 only after hard gates. Teacher rows provide representation targets only, never codec acoustic targets.

# Teacher distillation path

{training['teacher_rows']} weighted teacher rows pass through `acoustic_reference_features` and `model.distillation_prediction`; `weighted_distillation_loss` consumes recorded `trust_weight` with coefficient {training['teacher_loss_weight']}. Gradient tests prove timbre and language encoders receive non-zero teacher-loss gradients.

# Pseudo-singing generation and gates

ACE-Step-v1-3.5B (Apache-2.0) creates 100 KO/EN/JA a-cappella lyric candidates. Apache-2.0 SoulX SVC transfers GYU timbre. Gate requires RMVPE correlation ≥0.90, duration 0.85–1.15, WavLM ≥0.65, Whisper content ≥0.10, and matching transcript script-language. {accepted} rows pass; all rejections are evaluation-only. Provenance and metrics: `docs/pseudo_singing_report.md`.

# SVS concepts integrated

TCSinger-style blurred local context addresses hard boundaries; FM-Singer-style rectified flow generates codec latents; TechSinger-style presets and continuous controls enter `StyleEncoder`. Exact forward calls, losses, tests, and metric status: `docs/component_traceability.md`.

# Gradient connectivity evidence

`tests/test_hybrid.py::test_all_hybrid_modules_receive_gradient` checks every retained model module. `test_teacher_distillation_reaches_timbre_and_language_encoders` checks teacher-stage gradients. Full suite result recorded in this worktree: 22 passed.

# Training runs

CUDA, AdamW `2e-4`, batch 1, 1,200 steps; train rows {training['real_rows']} real + {training['pseudo_rows']} pseudo; validation/test 8/5. Final logged losses: total {last['loss']}, flow {last['flow']}, pitch {last['pitch']}, teacher {last['teacher']}. `artifacts/reports/hybrid_training.json` is full per-step evidence. GPU peak memory and wall-clock were not captured.

# Ablation results

`artifacts/reports/hybrid_teacher_ablation.json` contains short no-teacher versus weighted-teacher WavLM comparisons. It proves teacher branch changes output, not a quality gain.

# Baseline versus hybrid metrics

Current hybrid F0 correlation: KO {value(evaluation['ko']['hybrid_svs']['rmvpe_f0_correlation'])}, EN {value(evaluation['en']['hybrid_svs']['rmvpe_f0_correlation'])}, JA {value(evaluation['ja']['hybrid_svs']['rmvpe_f0_correlation'])}. ASR similarity: KO {value(evaluation['ko']['hybrid_svs']['asr_lyric_similarity'])}, EN {value(evaluation['en']['hybrid_svs']['asr_lyric_similarity'])}, JA {value(evaluation['ja']['hybrid_svs']['asr_lyric_similarity'])}. Full identical-score comparison: `docs/evaluation_v2_report.md`.

# Listening sample paths

`artifacts/samples/baseline_{{ko,en,ja}}.wav`, `artifacts/samples/hybrid_{{ko,en,ja}}.wav`, and `artifacts/samples/ablation_{{no_teacher,with_teacher}}_{{ko,en,ja}}.wav`.

# OpenUtau integration status

`integrations/openutau/bridge.py` reads `.ustx`, selects voice part, converts project ticks and first tempo to protocol v2 seconds, writes JSON, and can POST to resident `/render`. Tempo maps, native renderer registration, and editor curves are not implemented.

# Known failures

Generated hybrid F0 does not reliably follow score; intelligibility is weak; 3-second vowels are voiced but miss requested C4; real score labels are inferred; style controls uncalibrated; Korean-only real target data limits EN/JA evidence.

# Claims that are explicitly not being made

No v1 release, production singer, quality superiority over baseline, Japanese singing-quality support, annotated source singing scores, or teacher-data quality gain.

# Exact package commands

```sh
PYTHONPATH=src python scripts/package_v1.py
rm -rf /tmp/gyu-hybrid-smoke && mkdir /tmp/gyu-hybrid-smoke
unzip -q artifacts/package/gyu-hybrid-singer-v0.2-experimental.zip -d /tmp/gyu-hybrid-smoke
cd /tmp/gyu-hybrid-smoke/gyu-hybrid-singer-v0.2-experimental
PYTHONPATH=runtime python -m gyu_singer.cli --backend hybrid-svs --checkpoint model/gyu_hybrid_v0.2.pt --audio-tokenizer model/moss-audio-tokenizer-nano --reference model/gyu_reference_216.wav render examples/smoke.json --output output.wav
```

# Highest-value next steps

Add legal scored singing supervision with real EN/JA target data, train duration residuals and contour losses, capture held-out validation/telemetry, then rerun multi-seed listening and objective tests before reassessing v1.
"""
    Path("docs/training_v2_report.md").write_text(training_text)
    Path("docs/evaluation_v2_report.md").write_text(evaluation_text)
    Path("docs/final_v2_report.md").write_text(final_text)


if __name__ == "__main__":
    main()
