#!/usr/bin/env python3
"""Write reproducible legal pseudo-singing gate report."""
from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path


def rows(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text().splitlines() if line]


def metrics(items: list[dict], key: str) -> str:
    values = [float(item[key]) for item in items]
    return "n/a" if not values else f"{min(values):.4f}–{max(values):.4f}"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--candidates", default="data/manifests/pseudo_singing_candidates.jsonl")
    parser.add_argument("--output", default="docs/pseudo_singing_report.md")
    args = parser.parse_args()
    candidates = rows(Path(args.candidates))
    accepted = [row for row in candidates if row["quality_status"] == "accepted"]
    counts = Counter(row["language"] for row in candidates)
    accepted_counts = Counter(row["language"] for row in accepted)
    text = f"""# Pseudo-singing report

Generated by `scripts/report_ace_pseudo.py` from `{args.candidates}`. Candidate count: {len(candidates)} (KO {counts['ko']}, EN {counts['en']}, JA {counts['ja']}). Accepted: {len(accepted)} (KO {accepted_counts['ko']}, EN {accepted_counts['en']}, JA {accepted_counts['ja']}).

Pipeline: ACE-Step-v1-3.5B lyric-vocal generation (Apache-2.0, commit `1bee4c9f5b43e30995f8d4d33b3919197ce1bd68`) followed by SoulX Singer SVC (Apache-2.0). Every source candidate is a 10-second dry a-cappella phrase; prompts cover low/mid/high register, legato, repeated rhythm, vibrato, energetic, and breathy styles.

Gate: RMVPE F0 correlation ≥0.90, duration ratio 0.85–1.15, WavLM speaker cosine ≥0.65, Whisper content score ≥0.10, transcript-script language match, RMS ≥0.005, near-silence ≤0.75, and a unique 64-bin amplitude-envelope fingerprint. All candidates: F0 {metrics(candidates, 'f0_contour_correlation_rmvpe')}, duration {metrics(candidates, 'duration_ratio')}, speaker {metrics(candidates, 'speaker_score')}, content {metrics(candidates, 'content_score')}. Accepted only: F0 {metrics(accepted, 'f0_contour_correlation_rmvpe')}, speaker {metrics(accepted, 'speaker_score')}.

Only rows with `quality_status: accepted` and `training_license: allowed` may enter `prepare_hybrid_data.py`, at `trust_weight: 0.20`. Their note timing and pitch are explicitly `score_source: inferred_from_RMVPE_pitch_median_and_duration_not_ground_truth`; they are not source annotations. Rejected rows are evaluation-only and never acoustic training targets.
"""
    Path(args.output).write_text(text)


if __name__ == "__main__":
    main()
